/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oneclickbreadcontrol;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static oneclickbreadcontrol.OneClickbreadControl.gestion;
import static oneclickbreadcontrol.OneClickbreadControl.jefe;

/**
 *
 * @author Andres
 */
public class venMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form venMenuPrincipal
     */
    public venMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jFrame2 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        InvMen1 = new javax.swing.JMenu();
        Historia = new javax.swing.JMenu();
        Caja1 = new javax.swing.JMenu();
        CajDia1 = new javax.swing.JMenu();
        CajMensual1 = new javax.swing.JMenu();
        venta = new javax.swing.JMenu();
        ProvMen1 = new javax.swing.JMenu();
        ProyMen1 = new javax.swing.JMenu();
        InfMen1 = new javax.swing.JMenu();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Chioma Bakery");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jFrame3.setAlwaysOnTop(true);

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MenuPrincipal");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Chioma Bakery");

        Label.setText("Propietario");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );

        jButton1.setText("Cerrar sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        InvMen1.setText("Inventario");
        InvMen1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InvMen1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                InvMen1MenuSelected(evt);
            }
        });
        InvMen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvMen1MouseClicked(evt);
            }
        });
        InvMen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvMen1ActionPerformed(evt);
            }
        });

        Historia.setText("Historia");
        InvMen1.add(Historia);

        jMenuBar2.add(InvMen1);

        Caja1.setText("Caja");
        Caja1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CajDia1.setText("Diaria");
        CajDia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajDia1MouseClicked(evt);
            }
        });
        Caja1.add(CajDia1);

        CajMensual1.setText("Mensual");
        CajMensual1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajMensual1MouseClicked(evt);
            }
        });
        Caja1.add(CajMensual1);

        jMenuBar2.add(Caja1);

        venta.setText("Venta");
        venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventaMouseClicked(evt);
            }
        });
        jMenuBar2.add(venta);

        ProvMen1.setText("Proveedores");
        ProvMen1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProvMen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProvMen1MouseClicked(evt);
            }
        });
        jMenuBar2.add(ProvMen1);

        ProyMen1.setText("Proyecciones");
        ProyMen1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProyMen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProyMen1MouseClicked(evt);
            }
        });
        jMenuBar2.add(ProyMen1);

        InfMen1.setText("Informacion G");
        InfMen1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InfMen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfMen1MouseClicked(evt);
            }
        });
        jMenuBar2.add(InfMen1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Desktop))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 787, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InvMen1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_InvMen1MenuSelected
        // TODO add your handling code here:
        
                
                
    }//GEN-LAST:event_InvMen1MenuSelected

    private void InvMen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvMen1MouseClicked
        // TODO add your handling code here:
        venInventario inv = new venInventario();
        this.Desktop.add(inv);
        inv.show();
        
    }//GEN-LAST:event_InvMen1MouseClicked

    private void InvMen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvMen1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_InvMen1ActionPerformed

    private void CajDia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajDia1MouseClicked
        // TODO add your handling code here:
        venCajadiaria caj = new venCajadiaria();
        
       
        this.Desktop.add(caj);
        caj.show();
    }//GEN-LAST:event_CajDia1MouseClicked

    private void CajMensual1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajMensual1MouseClicked
        // TODO add your handling code here:
        venCajaMen men = new venCajaMen();
        this.Desktop.add(men);
        men.show();
    }//GEN-LAST:event_CajMensual1MouseClicked

    private void ProvMen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvMen1MouseClicked
        // TODO add your handling code here:
        venProveedores prov = new venProveedores();
        this.Desktop.add(prov);
        
        
        
        prov.show();
                
    }//GEN-LAST:event_ProvMen1MouseClicked

    private void ProyMen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProyMen1MouseClicked
        // TODO add your handling code here:
        venProyecciones proy = new venProyecciones();
        this.Desktop.add(proy);
        proy.show();
    }//GEN-LAST:event_ProyMen1MouseClicked

    private void InfMen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfMen1MouseClicked
        // TODO add your handling code here:
        venInformacionG inf = new  venInformacionG();
        this.Desktop.add(inf);
        inf.show();
    }//GEN-LAST:event_InfMen1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gestion.guardartodo(jefe);
        venIngresar ing = new venIngresar();
        ing.show();
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       gestion.guardartodo(jefe); // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseClicked
      venVentas ven = new venVentas();
      this.Desktop.add(ven);
      ven.show();// TODO add your handling code here:
    }//GEN-LAST:event_ventaMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CajDia1;
    private javax.swing.JMenu CajMensual1;
    private javax.swing.JMenu Caja1;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu Historia;
    private javax.swing.JMenu InfMen1;
    private javax.swing.JMenu InvMen1;
    private javax.swing.JLabel Label;
    private javax.swing.JMenu ProvMen1;
    private javax.swing.JMenu ProyMen1;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenu venta;
    // End of variables declaration//GEN-END:variables
}
